CREATE TABLE IF NOT EXISTS recovery_checkins (recovery_checkin_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, profile_id BIGINT NOT NULL REFERENCES profiles(profile_id), checkin_date DATE NOT NULL, sleep_hours NUMERIC(3,1) NOT NULL, soreness INTEGER NOT NULL CHECK (soreness BETWEEN 1 AND 10), stress INTEGER NOT NULL CHECK (stress BETWEEN 1 AND 10), pain_reported BOOLEAN NOT NULL DEFAULT FALSE, resting_hr_delta INTEGER NOT NULL DEFAULT 0, recovery_level TEXT NOT NULL CHECK (recovery_level IN ('Green','Yellow','Red')), recovery_score INTEGER NOT NULL CHECK (recovery_score BETWEEN 0 AND 100), notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS workout_recommendations (recommendation_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, profile_id BIGINT NOT NULL REFERENCES profiles(profile_id), target_date DATE NOT NULL, workout_type TEXT NOT NULL, title TEXT NOT NULL, instructions TEXT NOT NULL, duration_minutes INTEGER NOT NULL CHECK (duration_minutes BETWEEN 5 AND 360), intensity TEXT NOT NULL CHECK (intensity IN ('Very easy','Reduced','Normal')), home_alternative TEXT, rationale JSONB NOT NULL DEFAULT '[]'::JSONB, evidence JSONB NOT NULL DEFAULT '{}'::JSONB, status TEXT NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft','Approved','Completed','Skipped','Rejected')), approved_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS ix_recovery_checkins_profile_date ON recovery_checkins(profile_id,checkin_date DESC);
CREATE INDEX IF NOT EXISTS ix_workout_recommendations_profile_date ON workout_recommendations(profile_id,target_date DESC,status);
ALTER TABLE recovery_checkins ENABLE ROW LEVEL SECURITY; ALTER TABLE workout_recommendations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS personal_recovery_access ON recovery_checkins; CREATE POLICY personal_recovery_access ON recovery_checkins FOR ALL TO anon USING (profile_id=1) WITH CHECK (profile_id=1);
DROP POLICY IF EXISTS personal_recommendation_access ON workout_recommendations; CREATE POLICY personal_recommendation_access ON workout_recommendations FOR ALL TO anon USING (profile_id=1) WITH CHECK (profile_id=1);
GRANT SELECT,INSERT,UPDATE ON recovery_checkins TO anon; GRANT SELECT,INSERT,UPDATE ON workout_recommendations TO anon;
GRANT USAGE,SELECT ON SEQUENCE recovery_checkins_recovery_checkin_id_seq TO anon; GRANT USAGE,SELECT ON SEQUENCE workout_recommendations_recommendation_id_seq TO anon;
